import { Property } from './types';

export const INITIAL_PROPERTIES: Omit<Property, 'id'>[] = [
  {
    title: 'Modern Luxury Villa with Pool',
    category: 'House',
    listingType: 'sale',
    price: 850000,
    location: 'Beverly Hills, CA 90210',
    address: '123 Maple Drive',
    city: 'Beverly Hills',
    beds: 4,
    baths: 3,
    sqft: 2450,
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    description: 'Immaculate architectural masterpiece featuring panoramic floor-to-ceiling glass walls, an infinity-edge swimming pool, designer chef kitchen with marble waterfall islands, and private manicured grounds.',
    features: ['Swimming Pool', 'Central Air Conditioning', 'Smart Home Automation', 'Two-car Garage', 'Gourmet Kitchen', 'Walk-in Closet'],
    sellerId: 'demo-seller-1',
    sellerName: 'HomeLuxe Premier Estates',
    sellerEmail: 'concierge@homeluxe.com',
    sellerPhone: '(800) 123-4567',
    createdAt: Date.now() - 86400000 * 5,
    featured: true,
  },
  {
    title: 'Contemporary Cedar & Glass Residence',
    category: 'House',
    listingType: 'sale',
    price: 620000,
    location: 'Austin, TX 78701',
    address: '456 Oak Avenue',
    city: 'Austin',
    beds: 3,
    baths: 2,
    sqft: 1890,
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    description: 'Stunning contemporary multi-level home offering warm cedar accents, expansive rear deck, energy-efficient solar orientation, high ceilings, and an open concept perfect for hosting family and friends.',
    features: ['Attached Garage', 'Spacious Backyard', 'Hardwood Flooring', 'Solar Panels', 'EV Charger'],
    sellerId: 'demo-seller-2',
    sellerName: 'Sarah Jenkins',
    sellerEmail: 'sarah.j@homeluxe.com',
    sellerPhone: '(512) 555-0198',
    createdAt: Date.now() - 86400000 * 4,
    featured: true,
  },
  {
    title: 'Waterfront Glass Haven with Skyline Views',
    category: 'Apartment',
    listingType: 'rent',
    price: 3200,
    location: 'Miami, FL 33101',
    address: '789 Pine Street, Unit 5B',
    city: 'Miami',
    beds: 2,
    baths: 2,
    sqft: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    description: 'High-rise residence overlooking Biscayne Bay. Features wrap-around balconies, private elevator access, 24/7 concierge, resort-style rooftop swimming pool, fitness center, and marina slips.',
    features: ['Ocean View', 'Balcony', 'Concierge & Valet', 'Fitness Center', 'In-unit Laundry'],
    sellerId: 'demo-seller-3',
    sellerName: 'Marcus Vance',
    sellerEmail: 'm.vance@homeluxe.com',
    sellerPhone: '(305) 555-0142',
    createdAt: Date.now() - 86400000 * 3,
    featured: true,
  },
  {
    title: 'Cliffside Ocean View Coastal Retreat',
    category: 'House',
    listingType: 'sale',
    price: 1250000,
    location: 'San Diego, CA 92101',
    address: '321 Ocean View Drive',
    city: 'San Diego',
    beds: 2,
    baths: 4,
    sqft: 3100,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    description: 'Ultra-luxurious coastal retreat commanding breathtaking Pacific Ocean sunsets. Features heated outdoor lounges, built-in BBQ bar, wine tasting cellar, and multi-tier entertaining terraces.',
    features: ['Oceanfront Panorama', 'Wine Cellar', 'Spa / Hot Tub', 'Outdoor Kitchen', 'Designer Furnishings'],
    sellerId: 'demo-seller-1',
    sellerName: 'HomeLuxe Premier Estates',
    sellerEmail: 'concierge@homeluxe.com',
    sellerPhone: '(800) 123-4567',
    createdAt: Date.now() - 86400000 * 2,
    featured: true,
  },
  {
    title: 'Skyline View Penthouse Suite',
    category: 'Apartment',
    listingType: 'sale',
    price: 980000,
    location: 'Seattle, WA 98101',
    address: '550 4th Avenue, Penthouse 24',
    city: 'Seattle',
    beds: 3,
    baths: 3,
    sqft: 2150,
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    description: 'Soaring city views meet minimalist architectural perfection. Double-height ceilings, quartz countertops, custom walnut cabinetry, and private heated parking spots in the heart of downtown.',
    features: ['Penthouse Floor', 'Floor-to-Ceiling Windows', 'Custom Wine Wall', 'Private Terrace', 'Doorman'],
    sellerId: 'demo-seller-2',
    sellerName: 'Sarah Jenkins',
    sellerEmail: 'sarah.j@homeluxe.com',
    sellerPhone: '(206) 555-0821',
    createdAt: Date.now() - 86400000 * 1,
    featured: false,
  },
  {
    title: 'Sunset Ridge Residential Prime Plot',
    category: 'Plot',
    listingType: 'sale',
    price: 340000,
    location: 'Scottsdale, AZ 85251',
    address: 'Lot 14 Desert Vista Way',
    city: 'Scottsdale',
    beds: 0,
    baths: 0,
    sqft: 18500,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    description: 'Rare opportunity to construct your custom architectural dream estate. Fully graded premium residential land parcel with ready utility tie-ins (water, electric, gas, fiber-optic) and dramatic mountain vistas.',
    features: ['Approved Architectural Permits', 'Utilities On-Site', 'Mountain Views', 'Cul-de-sac Location', 'Gated Community Access'],
    sellerId: 'demo-seller-3',
    sellerName: 'Marcus Vance',
    sellerEmail: 'm.vance@homeluxe.com',
    sellerPhone: '(480) 555-0371',
    createdAt: Date.now(),
    featured: false,
  },
  {
    title: 'Lakeside Development Parcel with Private Shoreline',
    category: 'Plot',
    listingType: 'sale',
    price: 495000,
    location: 'Lake Tahoe, NV 89449',
    address: '88 Tahoe Shoreline Ridge',
    city: 'Lake Tahoe',
    beds: 0,
    baths: 0,
    sqft: 26000,
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: 'Expansive private building plot with grandfathered dock approval rights and pristine evergreen surroundings. Ready for custom alpine mountain sanctuary construction.',
    features: ['Direct Lake Access', 'Paved Road Access', 'Zoned Residential', 'Timber Clearing Done'],
    sellerId: 'demo-seller-1',
    sellerName: 'HomeLuxe Premier Estates',
    sellerEmail: 'concierge@homeluxe.com',
    sellerPhone: '(800) 123-4567',
    createdAt: Date.now() - 86400000 * 6,
    featured: false,
  },
  {
    title: 'Minimalist Garden Flat with Private Courtyard',
    category: 'Apartment',
    listingType: 'rent',
    price: 2400,
    location: 'Portland, OR 97201',
    address: '102 Northwest 10th Ave, Flat 3',
    city: 'Portland',
    beds: 1,
    baths: 1,
    sqft: 880,
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    description: 'Quiet, light-drenched flat featuring an internal tranquil bamboo courtyard, polished concrete floors, radiant heat, and custom Danish wood finishes.',
    features: ['Private Courtyard', 'Radiant Floor Heating', 'Pet Friendly', 'Bike Storage Room'],
    sellerId: 'demo-seller-2',
    sellerName: 'Sarah Jenkins',
    sellerEmail: 'sarah.j@homeluxe.com',
    sellerPhone: '(503) 555-0914',
    createdAt: Date.now() - 86400000 * 7,
    featured: false,
  }
];
